export const filesToDownload = [
  'mag2.jpeg',
  'clareou2.jpg',
  'dj1.jpeg',
  'decor1.jpg',
  'decor2.jpg',
  'ensaio10.jpg',
  'ensaio5.jpg',
  'festa4.jpg',
  'festa7.jpg',
  'infantil2.jpg',
  'infantil12.jpg',
  'infantil15.jpg',
  'bolofesta.jpg',
  'aniver7.JPG',
  'ellus.jpg',
  'barcas.jpg',
  'djdjondjon.jpg',
  'clareou1.jpg',
  'buda1.jpeg',
  'danca1.jpeg',
  'danca2.jpg',
  'dj1.jpeg',
  'dj9.jpeg',
  'djcutout.jpeg',
  'eyes1.jpeg',
  'fani1.jpeg',
  'esp13.jpg',
  'esp14.jpg',
  // 'esp15.jpg',
  'esp16.jpg',
  'esp19.jpg',
  // sessão em pé
  'quem1.jpeg',
  'anav1.jpeg',
  'eyes2.jpeg',
  'drink2.jpeg',
  'drink1.jpeg',
  // 'esp18.jpg',
  'catalogo1.jpg',
  'infantil11.jpg',
  'mag3.jpeg',
  'drink7.jpg',
  'ensaio7.jpg',
  'esp2.jpg',
  'esp1.jpg',
  'lora7.jpg',
  'judo1.jpeg',
  'mag1.jpeg',
  // sessão em pé
  // 'esp20.jpg',
  'esp17.jpg',
  'esp3.jpg',
  'esp8.jpg',
  'idoso1.JPG',
  'idoso2.JPG',
  'espkid1.JPG',
  'jp1.jpg',
  'jp2.jpg',
  'jp3.jpg',
  'jp4.jpg',
  'jp5.jpg',
  'jp6.jpg',
  'kids2.JPG',
  'kids3.JPG',
  'kids4.JPG',
  'kids5.JPG',
  'kids6.JPG',
  'kids7.JPG',
  'kids8.JPG',
  'lau1.jpg',
  'matheus1.jpg',
  'infantil13.jpg',
  'intantil14.jpg',
  // 'newborn1.jpg',
  // 'newborn2.jpg',
  // 'newborn3.jpg',
  // 'newborn4.jpg',
  'paIpanema.jpg',
  // 'self2.jpg',
  // 'self6.jpg',
  // 'self4.JPG',
  // 'off1.jpg',
  // 'off2.jpg',
  'self3.jpg',
  // sessão media
  'praianas3.jpeg',
  'off7.jpg',
  'off3.jpg',
  'off4.jpg',
  'festa1.jpeg',
  // sessão media
  'off5.jpg',
  // 'offju1.JPG',
  // 'offju2.JPG',
  'shows2.jpg',
  'shows3.jpg',
  'trem1.jpg',
  'ugo1.jpg',
  'ugo2.jpg',
  'ugopalco.jpg',
  'voice2.jpeg',
  'pri2.jpeg',
  'prof1.jpeg',
  'prof2.jpeg',
  'produto1.jpg',
  'pa3.jpg',
  'pri1.jpeg',
  'mumu1.jpeg',
  'thi1.jpeg'
];
